### ISSUE TITLE
Invalid Date of Issue

### ISSUE THREAD

**Issue by SHaagmann** [eiksch/statev_v3_issues#2998]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

16.02 22:31
**Beobachtetes Verhalten**

Auf dem Ausweis steht bei "Date of Issue" "Invalid Date"
**Erwartetes Verhalten**

Sollte das richtige Datum stehen
**Schritte um den Fehler nachvollziehen zu können**

Ausweis beantragen und anschauen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/c98c1f64-862a-44d4-a74f-fafb29ddb706)

**Comment by its4l3x** [comment]
fixed. kommt beim hotfix
