### ISSUE TITLE
Telefonat ablegen basedata is invalid

### ISSUE THREAD

**Issue by DrGrizzlY17** [eiksch/statev_v3_issues#2999]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Kayden Ryles

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23:15 16.2
**Beobachtetes Verhalten**
Wenn man das Telefonat auflegt kommt die Fehlermeldung unten im Screenshot. Optisch endet das telefonat aber man hört die andere Person immer noch

**Erwartetes Verhalten**
Telefonat sollte auch im voice enden

**Schritte um den Fehler nachvollziehen zu können**
Telefonat starten
mit N auflegen

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/a4b46339-aa7d-4714-a013-d0d9029ea1bd)

**Comment by coresync2k** [comment]
Den Fehler haben wir ebenfalls, selbst wenn man das Telefonat mit "drücken auf auflegen" beendet, kommt die Meldung bei dem der auflegt, und man hört alle immernoch

**Comment by simplycach** [comment]
Sind bereits dran.

**Comment by simplycach** [comment]
fixed
