### ISSUE TITLE
Fahrzeug Hotkeys nach Arbeit funktionieren nicht mehr

### ISSUE THREAD

**Issue by Pregon** [eiksch/statev_v3_issues#3000]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
David Danilov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Release 23:00

**Beobachtetes Verhalten**
Hotkeys Fahrzeug funktionieren nach Ölpumpen nicht mehr

**Erwartetes Verhalten**
Hotkeys funktionieren immer

**Schritte um den Fehler nachvollziehen zu können**
Öl machen, Fahrzeughotkeys testen

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hotkey/Funk bug](https://trello.com/c/ovxDVzlP/272-hotkey-funk-bug)

**Comment by simplycach** [comment]
nächstes Update fixed.
