### ISSUE TITLE
Einparken von Mietwagen

### ISSUE THREAD

**Issue by FLVFFY1** [eiksch/statev_v3_issues#3002]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Jayden_Banks**

**17.02.2024 0:30**

**Beobachtetes Verhalten**
Auf den Blip gefahren, auto war vollgetankt, gehupt, einparken bzw auto abgeben ging nicht

**Erwartetes Verhalten**
Mietwagen wird abgegeben / eingeparkt

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by CrazyKee** [comment]
Gab es eine Meldung dazu, dass das Fahrzeug nicht ausreichend betankt ist?

**Comment by FLVFFY1** [comment]
nope, keine meldung nichts leider

**Comment by Domeex3** [comment]
Trat das Problem bei dir noch mal auf?

**Comment by FLVFFY1** [comment]
sach wie es ist, aus irgendeinem grund war hupen bei mir auf "Y" - Einparken / abgeben ist aber E. deswegen gings nie, hab halt mit "Y" gehupt statte mit "E" -.-
